kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sre-challenge-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30500
    hostPort: 30500
    protocol: TCP
  - containerPort: 30600
    hostPort: 30600
    protocol: TCP