{
 "title": "SRE - kube-apiserver SLOs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"kube-apiserver\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Req/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{component=\"kube-apiserver\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( (sum(rate(apiserver_request_total{component=\"kube-apiserver\", code=~\"^[23]..$\"}[1h])) / sum(rate(apiserver_request_total{component=\"kube-apiserver\"}[1h]))) * 100 ) - 99.5",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency - GET/LIST",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{component=\"kube-apiserver\", verb=~\"GET|LIST\"}[5m])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability - HTTP (2xx/3xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(apiserver_request_total{component=\"kube-apiserver\", code=~\"^[23]..$\"}[5m])) / sum(rate(apiserver_request_total{component=\"kube-apiserver\"}[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}